pipeline{
  agent {
    docker {
      image 'python:2.7.16-slim'
      args '--user root'
    }
  }

  stages {
    stage('Build'){
      when {
        changeset "vote/**"
      }
      steps {
        echo 'Building vote app'
        dir('vote') {
          sh 'pip install -r requirements.txt'
        }
      }
    }
    
    stage('Test') {
      when {
        changeset "vote/**"
      }
      steps {
        echo 'Running unit tests'
        dir('vote') {
          sh 'nosetests -v'
        }
      }
    }
  }
}