pipeline {
  agent {
    docker {
      image 'maven:3.6.1-jdk-8-slim'
      arges '-v $HOME/.m2:/root/.m2'
    }
  }

  stages {
    stage('Build'){
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Building worker app'
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    
    stage('Test') {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Running unit tests'
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }

    stage('Package') {
      when {
        changeset "**/worker/**"
        branch 'master'
      }
      steps {
        echo 'Packaging'
        dir('worker'){
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*jar', fingerprint: true
        }
      }
    }
  }
}